###
# list databases (as admin)
http://127.0.0.1/mongodb/api
Authorization: Bearer xxx

###
# list database collections (as admin)
http://127.0.0.1/mongodb/api/auth
Authorization: Bearer xxx

###
# list collection items
http://127.0.0.1/mongodb/api/auth/users